# Generated by Django 4.1.6 on 2024-01-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
